defaults: &defaults
  terminal_types:
    content: Клеммы
    checkboxes:
      - :value: ''
        :label: T1
      - :value: ''
        :label: T13
  base_hold_down:
    content: Нижняя пластина
    checkboxes:
      - :value: B0
        :label: B0
      - :value: B01
        :label: B01
  layout:
    checkboxes:
      - :value: ''
        :label: "[+ - ] ПРЯМАЯ"
      - :value: ''
        :label: "[ - +] ОБРАТНАЯ"
      - :value: ''
        :label: "УНИВЕРСАЛЬНАЯ"
  voltage:
    si: В
    checkboxes:
      - :value: '6'
        :label: '6'
      - :value: '12'
        :label: '12'
  battery_capacity:
    si: А·ч
  cold_cranking_amps:
    si: А
    content: Ток холодной прокрутки
  length:
    si: мм
  width:
    si: мм
  height:
    si: мм

development:
  <<: *defaults

test:
  <<: *defaults

production:
  avtorif.ru:
    <<: *defaults
  zapstok.ru:
    <<: *defaults
