defaults: &defaults
  integration_mode: 'production'
  pass_1:           'password'
  pass_2:           'password'
  user:             'login'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  avtorif.ru:
    <<: *defaults
  zapstok.ru:
    <<: *defaults
