defaults: &defaults
  queue_adapter: :inline

development:
  <<: *defaults

test:
  <<: *defaults

production:
  avtorif.ru:
    <<: *defaults
    queue_adapter: :sidekiq
  zapstok.ru:
    <<: *defaults
    queue_adapter: :sidekiq
