defaults: &defaults
  integration_mode: :test
  user:             avtorif
  pass1:            vjqgfhjkm1
  pass2:            vjqgfhjkm2

development:
  <<: *defaults

test:
  <<: *defaults

production:
  avtorif.ru:
    <<: *defaults
    integration_mode: :test
  zapstok.ru:
    <<: *defaults
    :integration_mode: :test
