defaults: &defaults
  integration_mode: :test
  pass_1:           password
  pass_2:           password
  user:             login

development:
  <<: *defaults

test:
  <<: *defaults

production:
  avtorif.ru:
    <<: *defaults
    integration_mode: :production
  zapstok.ru:
    <<: *defaults
    :integration_mode: :production
