defaults: &defaults
  tables:
  - cars
  - bots
  - brands
  - models
  - generations
  - modifications
  - faqs
  - spare_catalogs
  - spare_infos
  - spare_replacements
  - spare_applicabilities

development:
  <<: *defaults

test:
  <<: *defaults

production:
  avtorif.ru:
    <<: *defaults
  zapstok.ru:
    <<: *defaults
