defaults: &defaults
  account: Номер счета получателя платежа
  bank: Наименование банка получателя платежа
  bik: БИК
  correspondent: Номер кор./сч. банка получателя платежа
  inn: ИНН получателя платежа (не банка)
  recipient: Наименования получателя платежа

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

