defaults: &defaults
  checkout_account: Номер счета получателя платежа
  checkout_bank: Наименование банка получателя платежа
  checkout_bik: БИК
  checkout_correspondent: Номер кор./сч. банка получателя платежа
  checkout_inn: ИНН получателя платежа (не банка)
  checkout_recipient: Наименования получателя платежа

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

