defaults: &defaults
  suppress_exceptions: true
  login: 'woto'
  password: 'woto'

development:
  <<: *defaults
  suppress_exceptions: false

test:
  <<: *defaults

production:
  avtorif.ru:
    <<: *defaults
  zapstok.ru:
    <<: *defaults
