defaults: &defaults
  enabled: true
  root: false

development:
  <<: *defaults
  enabled: false
  root: false

test:
  <<: *defaults

production:
  avtorif.ru:
    <<: *defaults
  zapstok.ru:
    <<: *defaults
