defaults: &defaults
  share_buttons: true
  suppress_exceptions: true

development:
  <<: *defaults
  share_buttons: false
  suppress_exceptions: false

test:
  <<: *defaults
  share_buttons: false

production:
  avtorif.ru:
    <<: *defaults
  zapstok.ru:
    <<: *defaults
