defaults: &defaults
  share_buttons: false
  suppress_exceptions: false
  display_tawk_to: false
  display_counters: false
  mail: "Авториф <info@avtorif.ru>"

development:
  <<: *defaults

test:
  <<: *defaults
  suppress_exceptions: true

production:
  <<: *defaults
  share_buttons: true
  suppress_exceptions: true
  display_tawk_to: true
  display_counters: true

staging:
  <<: *defaults
