defaults: &defaults
  host: '192.168.1.252'
  port: '80'
  api_username: woto
  host_port: 'forum.avtorif.ru'
  api_key: 0b7e161b9c70e33b05eb5d2d818c48c06b5db1bf587b41c5df8baf123ccc2958

development:
  <<: *defaults

test:
  <<: *defaults

production:
  avtorif.ru:
    <<: *defaults
    host: 'forum.avtorif.ru'
    port: '80'
    api_username: woto
    host_port: 'forum.avtorif.ru'
    api_key: 0b7e161b9c70e33b05eb5d2d818c48c06b5db1bf587b41c5df8baf123ccc2958
  zapstok.ru:
    <<: *defaults
