defaults: &defaults
  host: '192.168.1.252'
  port: '80'
  host_port: '192.168.1.252'
  api_username: woto
  api_key: d6ea0420ccfdc50b42b84605965d2eaacfa3ab543b4ae5548f944480f15351c1

development:
  <<: *defaults

test:
  <<: *defaults

production:
  avtorif.ru:
    <<: *defaults
    host_port: 'http://forum.avtorif.ru'
  zapstok.ru:
    <<: *defaults
