defaults: &defaults
  delivery_method:
  from:
  smtp_address:
  smtp_port:
  smtp_user_name:
  smtp_password:
  smtp_authentication:
  smtp_enable_starttls_auto:

development:
  <<: *defaults

test:
  <<: *defaults
  delivery_method: 'test'

production:
  <<: *defaults
  delivery_method:           'smtp'
  from:                      'Авториф <info@avtorif.ru>'
  smtp_address:              'smtp.yandex.ru'
  smtp_port:                 25
  smtp_user_name:            'info@avtorif.ru'
  smtp_password:             'ASD123qwe'
  smtp_authentication:       'plain'
  smtp_enable_starttls_auto: false
