defaults: &defaults
  delivery_method:           smtp
  from:                      Отправитель <robot@example.com>
  smtp_settings:
    :address:                smtp.example.com
    :port:                   25
    :user_name:              robot@example.com

development:
  <<: *defaults

test:
  <<: *defaults
  delivery_method: 'test'

production:
  <<: *defaults
  delivery_method:           smtp
  from:                      Авториф <info@avtorif.ru>
  smtp_settings:
    :address:                smtp.yandex.ru
    :port:                   465
    :user_name:              info@avtorif.ru
    :password:               ASD123qwe
    :authentication:         plain
    :enable_starttls_auto:   true
    :ssl:                    true
