defaults: &defaults
  price_request_cache_with_replacements_in_seconds: 1
  price_request_cache_without_replacements_in_seconds: 1
  host: 'localhost'
  port: '3001'

  request_emex: false
  emex_income_rate: 1.05 # Наценка 5%
  avtorif_income_rate: 1 # Скидка 19.98% TODO он не будет использоваться
  retail_rate: 1

  send_request_from_search_page: true

development:
  <<: *defaults
  host: 'avtorif.ru'
  port: '85'

test:
  <<: *defaults
  host: 'localhost'
  port: 3001

production:
  <<: *defaults
  price_request_cache_with_replacements_in_seconds: 7776000 # 3 мес.
  price_request_cache_without_replacements_in_seconds: 3600 #  1 час.
  host: 'avtorif.ru'
  port: '85'
