defaults: &defaults
  host: localhost
  port: 3001

  price_request_cache_with_replacements_in_seconds: 7776000 # 3 мес.
  price_request_cache_without_replacements_in_seconds: 3600 #  1 час.

  request_emex: false

development:
  <<: *defaults
  price_request_cache_with_replacements_in_seconds: 1
  price_request_cache_without_replacements_in_seconds: 1

test:
  <<: *defaults

production:
  <<: *defaults
  host: partners.avtorif.ru
  port: 80

staging:
  <<: *defaults
