defaults: &defaults
  host: '192.168.1.253'
  port: '3000'
  host_port: '192.168.1.253'

development:
  <<: *defaults

test:
  <<: *defaults
  host: 'test.host'
  port: '80'
  host_port: 'test.host'

production:
  <<: *defaults
  host: 'avtorif.ru'
  port: '80'
  host_port: 'avtorif.ru'

staging:
  <<: *defaults
