defaults: &defaults

development:
  <<: *defaults
  host: 'localhost'
  port: '3002'

test:
  <<: *defaults
  host: 'test.host'
  port: '80'

production:
  <<: *defaults
  host: 'avtorif.ru'
  port: '80'
