defaults: &defaults

development:
  <<: *defaults
  host: '192.168.1.253'
  port: '3002'

test:
  <<: *defaults
  host: 'test.host'
  port: '80'

production:
  avtorif.ru:
    <<: *defaults
    host: 'avtorif.ru'
    port: '80'
  zapstok.ru:
    <<: *defaults
    host: 'zapstok.ru'
    port: '80'
