defaults: &defaults
  default:
   prepayment: 20
   discount: 0
   order_rule: 'all'
   role: 'guest'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  avtorif.ru:
    <<: *defaults
  zapstok.ru:
    <<: *defaults
