defaults: &defaults
  truck_tire_width:
    si:
    checkboxes:
      - :value: '0'
        :label: '7'
      - :value: '1'
        :label: '7.5'
      - :value: '2'
        :label: '8.25'
      - :value: '3'
        :label: '9'
      - :value: '4'
        :label: '10'
      - :value: '5'
        :label: '11'
      - :value: '6'
        :label: '12'
      - :value: '7'
        :label: '215'
      - :value: '8'
        :label: '235'
      - :value: '9'
        :label: '265'
      - :value: '10'
        :label: '275'
      - :value: '11'
        :label: '295'
      - :value: '12'
        :label: '315'
      - :value: '13'
        :label: '385'
  truck_tire_height:
    si:
    checkboxes:
      - :value: '0'
        :label: '65'
      - :value: '1'
        :label: '75'
      - :value: '2'
        :label: '80'
      - :value: '3'
        :label: '70'
  truck_tire_diameter:
    si:
    checkboxes:
      - :value: '0'
        :label: '16'
      - :value: '1'
        :label: '17.5'
      - :value: '2'
        :label: '19.5'
      - :value: '3'
        :label: '20'
      - :value: '4'
        :label: '22.5'
      - :value: '5'
        :label: '24'
  truck_tire_speed:
    si:
    checkboxes:
      - :value: '0'
        :label: 'J'
      - :value: '1'
        :label: 'K'
      - :value: '2'
        :label: 'L'
      - :value: '3'
        :label: 'M'
  truck_tire_load:
    si:
    checkboxes:
      - :value: '0'
        :label: '122/118'
      - :value: '1'
        :label: '126/124'
      - :value: '2'
        :label: '132/130'
      - :value: '3'
        :label: '143/141'
      - :value: '4'
        :label: '144/142'
      - :value: '5'
        :label: '146/143'
      - :value: '6'
        :label: '148/145'
      - :value: '7'
        :label: '149/145'
      - :value: '8'
        :label: '150/147'
      - :value: '9'
        :label: '152/148'
      - :value: '10'
        :label: '154/150'
      - :value: '11'
        :label: '154/151'
      - :value: '12'
        :label: '158/155'

  truck_tire_line:
    si:
    checkboxes:
      - :value: '0'
        :label: 'CST 18'
      - :value: '1'
        :label: 'CST 27'
      - :value: '2'
        :label: 'CST 35'
      - :value: '3'
        :label: 'CST 46'
      - :value: '4'
        :label: 'CST 56'
      - :value: '5'
        :label: 'CST 68'
      - :value: '6'
        :label: 'CST 78'
  truck_tire_axle:
    si:
    checkboxes:
      - :value: '0'
        :label: 'Рулевое'
      - :value: '1'
        :label: 'Ведущее'
      - :value: '2'
        :label: 'Прицеп'
      - :value: '3'
        :label: 'Рулевое-прицеп'
      - :value: '4'
        :label: 'Универсальная ось'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  avtorif.ru:
    <<: *defaults
  zapstok.ru:
    <<: *defaults

