require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Content::FilesController do

  # This should return the minimal set of attributes required to create a valid
  # Content::File. As you add validations to Content::File, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "file" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Content::FilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all content_files as @content_files" do
      file = Content::File.create! valid_attributes
      get :index, {}, valid_session
      assigns(:content_files).should eq([file])
    end
  end

  describe "GET show" do
    it "assigns the requested content_file as @content_file" do
      file = Content::File.create! valid_attributes
      get :show, {:id => file.to_param}, valid_session
      assigns(:content_file).should eq(file)
    end
  end

  describe "GET new" do
    it "assigns a new content_file as @content_file" do
      get :new, {}, valid_session
      assigns(:content_file).should be_a_new(Content::File)
    end
  end

  describe "GET edit" do
    it "assigns the requested content_file as @content_file" do
      file = Content::File.create! valid_attributes
      get :edit, {:id => file.to_param}, valid_session
      assigns(:content_file).should eq(file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Content::File" do
        expect {
          post :create, {:content_file => valid_attributes}, valid_session
        }.to change(Content::File, :count).by(1)
      end

      it "assigns a newly created content_file as @content_file" do
        post :create, {:content_file => valid_attributes}, valid_session
        assigns(:content_file).should be_a(Content::File)
        assigns(:content_file).should be_persisted
      end

      it "redirects to the created content_file" do
        post :create, {:content_file => valid_attributes}, valid_session
        response.should redirect_to(Content::File.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved content_file as @content_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        Content::File.any_instance.stub(:save).and_return(false)
        post :create, {:content_file => { "file" => "invalid value" }}, valid_session
        assigns(:content_file).should be_a_new(Content::File)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Content::File.any_instance.stub(:save).and_return(false)
        post :create, {:content_file => { "file" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested content_file" do
        file = Content::File.create! valid_attributes
        # Assuming there are no other content_files in the database, this
        # specifies that the Content::File created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Content::File.any_instance.should_receive(:update).with({ "file" => "MyString" })
        put :update, {:id => file.to_param, :content_file => { "file" => "MyString" }}, valid_session
      end

      it "assigns the requested content_file as @content_file" do
        file = Content::File.create! valid_attributes
        put :update, {:id => file.to_param, :content_file => valid_attributes}, valid_session
        assigns(:content_file).should eq(file)
      end

      it "redirects to the content_file" do
        file = Content::File.create! valid_attributes
        put :update, {:id => file.to_param, :content_file => valid_attributes}, valid_session
        response.should redirect_to(file)
      end
    end

    describe "with invalid params" do
      it "assigns the content_file as @content_file" do
        file = Content::File.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Content::File.any_instance.stub(:save).and_return(false)
        put :update, {:id => file.to_param, :content_file => { "file" => "invalid value" }}, valid_session
        assigns(:content_file).should eq(file)
      end

      it "re-renders the 'edit' template" do
        file = Content::File.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Content::File.any_instance.stub(:save).and_return(false)
        put :update, {:id => file.to_param, :content_file => { "file" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested content_file" do
      file = Content::File.create! valid_attributes
      expect {
        delete :destroy, {:id => file.to_param}, valid_session
      }.to change(Content::File, :count).by(-1)
    end

    it "redirects to the content_files list" do
      file = Content::File.create! valid_attributes
      delete :destroy, {:id => file.to_param}, valid_session
      response.should redirect_to(content_files_url)
    end
  end

end
