require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Content::TextsController do

  # This should return the minimal set of attributes required to create a valid
  # Content::Text. As you add validations to Content::Text, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "text" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Content::TextsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all content_texts as @content_texts" do
      text = Content::Text.create! valid_attributes
      get :index, {}, valid_session
      assigns(:content_texts).should eq([text])
    end
  end

  describe "GET show" do
    it "assigns the requested content_text as @content_text" do
      text = Content::Text.create! valid_attributes
      get :show, {:id => text.to_param}, valid_session
      assigns(:content_text).should eq(text)
    end
  end

  describe "GET new" do
    it "assigns a new content_text as @content_text" do
      get :new, {}, valid_session
      assigns(:content_text).should be_a_new(Content::Text)
    end
  end

  describe "GET edit" do
    it "assigns the requested content_text as @content_text" do
      text = Content::Text.create! valid_attributes
      get :edit, {:id => text.to_param}, valid_session
      assigns(:content_text).should eq(text)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Content::Text" do
        expect {
          post :create, {:content_text => valid_attributes}, valid_session
        }.to change(Content::Text, :count).by(1)
      end

      it "assigns a newly created content_text as @content_text" do
        post :create, {:content_text => valid_attributes}, valid_session
        assigns(:content_text).should be_a(Content::Text)
        assigns(:content_text).should be_persisted
      end

      it "redirects to the created content_text" do
        post :create, {:content_text => valid_attributes}, valid_session
        response.should redirect_to(Content::Text.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved content_text as @content_text" do
        # Trigger the behavior that occurs when invalid params are submitted
        Content::Text.any_instance.stub(:save).and_return(false)
        post :create, {:content_text => { "text" => "invalid value" }}, valid_session
        assigns(:content_text).should be_a_new(Content::Text)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Content::Text.any_instance.stub(:save).and_return(false)
        post :create, {:content_text => { "text" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested content_text" do
        text = Content::Text.create! valid_attributes
        # Assuming there are no other content_texts in the database, this
        # specifies that the Content::Text created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Content::Text.any_instance.should_receive(:update).with({ "text" => "MyText" })
        put :update, {:id => text.to_param, :content_text => { "text" => "MyText" }}, valid_session
      end

      it "assigns the requested content_text as @content_text" do
        text = Content::Text.create! valid_attributes
        put :update, {:id => text.to_param, :content_text => valid_attributes}, valid_session
        assigns(:content_text).should eq(text)
      end

      it "redirects to the content_text" do
        text = Content::Text.create! valid_attributes
        put :update, {:id => text.to_param, :content_text => valid_attributes}, valid_session
        response.should redirect_to(text)
      end
    end

    describe "with invalid params" do
      it "assigns the content_text as @content_text" do
        text = Content::Text.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Content::Text.any_instance.stub(:save).and_return(false)
        put :update, {:id => text.to_param, :content_text => { "text" => "invalid value" }}, valid_session
        assigns(:content_text).should eq(text)
      end

      it "re-renders the 'edit' template" do
        text = Content::Text.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Content::Text.any_instance.stub(:save).and_return(false)
        put :update, {:id => text.to_param, :content_text => { "text" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested content_text" do
      text = Content::Text.create! valid_attributes
      expect {
        delete :destroy, {:id => text.to_param}, valid_session
      }.to change(Content::Text, :count).by(-1)
    end

    it "redirects to the content_texts list" do
      text = Content::Text.create! valid_attributes
      delete :destroy, {:id => text.to_param}, valid_session
      response.should redirect_to(content_texts_url)
    end
  end

end
