# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d7c47c97c917cf1fe9b4c753cc7410dd72ca9b83f04c91ff8cf18530b9802812536a859037a168965d8f99ac5f97ca2cea8aeab1e87f1abc6f09d1afa821c76

test:
  secret_key_base: a9742236cdf53a527e15dde69fb33abfcf36631ea302ad88fb7c9cf04d96d4a5bf8cef676e810f97a9c2d31e68bf9ec362ed15191ee13b2f2f20c35d5de48554

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
