require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpareCatalogsController do

  # This should return the minimal set of attributes required to create a valid
  # SpareCatalog. As you add validations to SpareCatalog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpareCatalogsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all spare_catalogs as @spare_catalogs" do
      spare_catalog = SpareCatalog.create! valid_attributes
      get :index, {}, valid_session
      assigns(:spare_catalogs).should eq([spare_catalog])
    end
  end

  describe "GET show" do
    it "assigns the requested spare_catalog as @spare_catalog" do
      spare_catalog = SpareCatalog.create! valid_attributes
      get :show, {:id => spare_catalog.to_param}, valid_session
      assigns(:spare_catalog).should eq(spare_catalog)
    end
  end

  describe "GET new" do
    it "assigns a new spare_catalog as @spare_catalog" do
      get :new, {}, valid_session
      assigns(:spare_catalog).should be_a_new(SpareCatalog)
    end
  end

  describe "GET edit" do
    it "assigns the requested spare_catalog as @spare_catalog" do
      spare_catalog = SpareCatalog.create! valid_attributes
      get :edit, {:id => spare_catalog.to_param}, valid_session
      assigns(:spare_catalog).should eq(spare_catalog)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SpareCatalog" do
        expect {
          post :create, {:spare_catalog => valid_attributes}, valid_session
        }.to change(SpareCatalog, :count).by(1)
      end

      it "assigns a newly created spare_catalog as @spare_catalog" do
        post :create, {:spare_catalog => valid_attributes}, valid_session
        assigns(:spare_catalog).should be_a(SpareCatalog)
        assigns(:spare_catalog).should be_persisted
      end

      it "redirects to the created spare_catalog" do
        post :create, {:spare_catalog => valid_attributes}, valid_session
        response.should redirect_to(SpareCatalog.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved spare_catalog as @spare_catalog" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpareCatalog.any_instance.stub(:save).and_return(false)
        post :create, {:spare_catalog => { "title" => "invalid value" }}, valid_session
        assigns(:spare_catalog).should be_a_new(SpareCatalog)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpareCatalog.any_instance.stub(:save).and_return(false)
        post :create, {:spare_catalog => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested spare_catalog" do
        spare_catalog = SpareCatalog.create! valid_attributes
        # Assuming there are no other spare_catalogs in the database, this
        # specifies that the SpareCatalog created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SpareCatalog.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => spare_catalog.to_param, :spare_catalog => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested spare_catalog as @spare_catalog" do
        spare_catalog = SpareCatalog.create! valid_attributes
        put :update, {:id => spare_catalog.to_param, :spare_catalog => valid_attributes}, valid_session
        assigns(:spare_catalog).should eq(spare_catalog)
      end

      it "redirects to the spare_catalog" do
        spare_catalog = SpareCatalog.create! valid_attributes
        put :update, {:id => spare_catalog.to_param, :spare_catalog => valid_attributes}, valid_session
        response.should redirect_to(spare_catalog)
      end
    end

    describe "with invalid params" do
      it "assigns the spare_catalog as @spare_catalog" do
        spare_catalog = SpareCatalog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpareCatalog.any_instance.stub(:save).and_return(false)
        put :update, {:id => spare_catalog.to_param, :spare_catalog => { "title" => "invalid value" }}, valid_session
        assigns(:spare_catalog).should eq(spare_catalog)
      end

      it "re-renders the 'edit' template" do
        spare_catalog = SpareCatalog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpareCatalog.any_instance.stub(:save).and_return(false)
        put :update, {:id => spare_catalog.to_param, :spare_catalog => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested spare_catalog" do
      spare_catalog = SpareCatalog.create! valid_attributes
      expect {
        delete :destroy, {:id => spare_catalog.to_param}, valid_session
      }.to change(SpareCatalog, :count).by(-1)
    end

    it "redirects to the spare_catalogs list" do
      spare_catalog = SpareCatalog.create! valid_attributes
      delete :destroy, {:id => spare_catalog.to_param}, valid_session
      response.should redirect_to(spare_catalogs_url)
    end
  end

end
