require 'test_helper'

class Admin::Deliveries::PlacesControllerTest < ActionController::TestCase
  test 'Минимальный тест на создание зоны доставки' do
    assert_difference -> {Deliveries::Place.count} do
      post :create, deliveries_place: {
        "partner"=>"0",
        "active"=>"1",
        "z_index"=>"100",
        "realize"=>"1",
        "name"=>"Название",
        "metro"=>"",
        "content"=>"",
        "variants_attributes"=>
         {"0"=>{"_destroy"=>"false", "name"=>"Курьер", "active"=>"1", "sequence"=>"10", "delivery_cost"=>"100", "option_id"=>"", "content"=>""}},
        "display_marker"=>"0",
        "phone1"=>"",
        "phone2"=>"",
        "phone3"=>"",
        "phone4"=>"",
        "phone5"=>"",
        "email1"=>"",
        "email2"=>"",
        "email3"=>"",
        "address_locality"=>"",
        "postal_code"=>"",
        "street_address"=>"",
        "price_url"=>"",
        "remote_image1_url"=>"",
        "remove_image1"=>"0",
        "image1_cache"=>"",
        "remote_image2_url"=>"",
        "remove_image2"=>"0",
        "image2_cache"=>"",
        "remote_image3_url"=>"",
        "remove_image3"=>"0",
        "image3_cache"=>"",
        "remote_image4_url"=>"",
        "remove_image4"=>"0",
        "image4_cache"=>"",
        "remote_image5_url"=>"",
        "remove_image5"=>"0",
        "image5_cache"=>"",
        "active_fill_color"=>"#000000",
        "active_fill_opacity"=>"0.5",
        "active_stroke_color"=>"#000000",
        "active_stroke_opacity"=>"0.5",
        "active_stroke_weight"=>"0.5",
        "inactive_fill_color"=>"#000000",
        "inactive_fill_opacity"=>"0.5",
        "inactive_stroke_color"=>"#000000",
        "inactive_stroke_opacity"=>"0.5",
        "inactive_stroke_weight"=>"0.5",
        "vertices"=>"ijksIqlodFpvDxtA?ybH{iE?",
        "lat"=>"55.65768637885181",
        "lng"=>"37.673236582946856",
        "zoom"=>"10",
        "ycountry"=>"",
        "ycountry_code"=>"",
        "ycity"=>"",
        "ystreet"=>"",
        "yhouse"=>"",
        "ycity_code"=>"",
        "yphone"=>"",
        "ycompany_name"=>"",
        "ycontact_email"=>"",
        "ywork_time"=>"",
        "yogrn"=>""}
    end
  end
end
